{% set name = "quantile-forest" %}
{% set version = "1.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quantile_forest-{{ version }}.tar.gz
  sha256: 020bb88bb110bbdab461776fde8150c3503e76fde3cf0f51d4fd3119c6ce2f89

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - wheel
    - cython >=3.0a4
    - numpy >=1.23
    - scipy >=1.4
    - scikit-learn >=1.0
    - pip
  run:
    - python
    - scipy >=1.4
    - scikit-learn >=1.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - examples
    - quantile_forest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://zillow.github.io/quantile-forest
  summary: scikit-learn compatible quantile forests.
  dev_url: https://github.com/zillow/quantile-forest
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - reidjohnson
